### ISSUE TITLE
Viewer: Highlighted gridlines are not displayed

### ISSUE THREAD

**Issue by vcyas2020** [groupdocs-total/GroupDocs.Total-Angular#224]
If you view an excel file with pre-defined highlighted gridlines, they are not displayed in the viewer.

**Comment by bobkovalex** [comment]
Hi @vcyas2020 

Thank you for submitting feedback.

Please checkout latest commit from GroupDocs.Total-for-NET-MVC/Webforms master branch and set **showGridLines** as **true** in configuration.yml
https://github.com/groupdocs-total/GroupDocs.Total-for-NET-MVC/blob/master/src/configuration.yml#L94

Thanks.
Regards

**Comment by vcyas2020** [comment]
Hi @bobkovalex ,

I've checked the the latest code here and also the implementation in the backend. Issues still occurs

1. setting showGridLines only display the gridlines but not the highlighted ones
2. row numbers still appears inside the rendered excel sheet due to tables within tables.

Thanks!

**Comment by bobkovalex** [comment]
Hi @vcyas2020 

I apologise for not replying sooner.
Would you please share some screenshots and excel files so that we can better understand what exactly is wrong?
Thanks.

Regards
