### ISSUE TITLE
Angular Viewer display problems

### ISSUE THREAD

**Issue by JeepLavoie** [groupdocs-total/GroupDocs.Total-Angular#289]
Hi,

First of all I don't know if I made the issue in the good Repository. We are using the nuget GroupDocs.Viewer.UI.SelfHost.Api, but since the problem are more within the npm package that the nuget, I was thinking that this repository was the good one to open the issue directly. 

We had some problems with `@groupdocs.examples.angular/viewer` 

## Navigation and Zoom

The first one it's when using Zoom and _cropping_ a part of the View Box the page count don't follow. You can see the two behaviour with those two videos 

https://github.com/groupdocs-total/GroupDocs.Total-Angular/assets/3975143/e16ff403-6b62-4aa3-b903-9a69f168daa5

https://github.com/groupdocs-total/GroupDocs.Total-Angular/assets/3975143/380c463e-072d-472e-9edf-a41ef63b1b72

This is the file use in the videos : [repro-pdf-1.pdf](https://github.com/groupdocs-total/GroupDocs.Total-Angular/files/12088574/SGT-Information-et-sensibilisation-1.pdf)

## Looping Navigation

The second one it's the inverse, when we are zooming out with a document of many pages, using the Chevron navigation, we are looping around the page that they are shown in the page.

https://github.com/groupdocs-total/GroupDocs.Total-Angular/assets/3975143/be9d60bb-49e4-4cca-a124-f71979f3555c

This is the file use in this video : [repro-pdf-2.pdf](https://github.com/groupdocs-total/GroupDocs.Total-Angular/files/12088576/large.pdf.pdf)

We are using `GroupDocs.Viewer.UI.SelfHost.Api` version 6.0.15, so we are using `@groupdocs.examples.angular/viewer` at version 0.8.100

Thanks 😃

**Comment by vladimir-litvinchik** [comment]
@JeepLavoie 

Thank you for sharing the videos and the source file for each of them. We'll take a look and update you.

**Comment by CmortonDCM** [comment]
Hi Vladimir, are these still the latest versions of these?

GroupDocs.Viewer.UI package to 6.0.14.
@groupdocs.examples.angular/viewer package version is 0.8.103 now.

**Comment by vladimir-litvinchik** [comment]
@CmortonDCM 

The actual versions are:

* GroupDocs.Viewer.UI 6.0.27
* @groupdocs.examples.angular/viewer 0.8.112

**Comment by vladimir-litvinchik** [comment]
@CmortonDCM 

No, that app uses a different UI. At the moment we're configuring UI from https://products.groupdocs.app/viewer/total to be used in `GroupDocs.Viewer.UI` package. We expect to complete the transition by the end of this month.

**Comment by CmortonDCM** [comment]
Thanks Vladimir. Do you have a date that this new package will be released?

**Comment by vladimir-litvinchik** [comment]
@CmortonDCM 

We plan to release it by the end of this month in case we won't have any unexpected issues. Will update you here.

**Comment by CmortonDCM** [comment]
@vladimir-litvinchik 

Was this package released?

**Comment by vladimir-litvinchik** [comment]
@CmortonDCM 

It is still under development. The code can be found at https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-UI/tree/angular-app/migrate-viewer-apps-ui.

**Comment by CmortonDCM** [comment]
@vladimir-litvinchik 
Does that mean we shouldn't use it if it's still under development or is it ok to use and there will be an update at some point?

**Comment by vladimir-litvinchik** [comment]
@CmortonDCM 

I would not recommend using it now. At the moment we're testing it and integrating the required changes. The final version may differ from this one so I would rather wait for a week or two when it will be published.

**Comment by CmortonDCM** [comment]
ok thanks, I'll follow up in a couple weeks.

**Comment by CmortonDCM** [comment]
@vladimir-litvinchik 

Hi, has the final version of this been published?

**Comment by CmortonDCM** [comment]
ok thanks @vladimir-litvinchik 

Any idea when the issues may be resolved? Are we looking at days or weeks?

**Comment by vladimir-litvinchik** [comment]
@CmortonDCM 

Sorry for the inconvenience. We're working on it. Will let you know the ETA next week.

**Comment by CmortonDCM** [comment]
@vladimir-litvinchik

Do you have any updare on the release date for this version?

**Comment by vladimir-litvinchik** [comment]
@CmortonDCM 

Yes, we plan to publish the new version by the end of this week. There are a couple of issues that have to be fixed which relate to Angular UI. 

You can test the latest version by pulling [angular-app/migrate-ui-and-api](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-UI/compare/angular-app/migrate-ui-and-api) branch.

This branch will be used to publish packages after we fix the issues.

**Comment by vladimir-litvinchik** [comment]
@CmortonDCM 

We have published the updated version of Angular UI in  the latest version of GroupDocs.Viewer.UI package.
See the repository page: https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-UI/tree/main.

The app itself can be found in https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-UI/tree/main/src/GroupDocs.Viewer.UI/App folder.

Angular app sources is still highly coupled with https://products.groupdocs.app/viewer/total so we do not have ETA when we'll be able to publish them to GitHub.
